# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.define "host1" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|
         vb.memory = "128"
         vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      end
      node.vm.hostname = "tenant1-host1"
      node.vm.network :private_network, virtualbox__intnet: "n9k1-eth12", mac: "0800F7760102", ip: "192.168.0.11", auto_config: false
      node.vm.provision "shell", inline: <<-SHELL
         ip addr add 192.168.0.11/24 dev eth1
      SHELL
  end
  config.vm.define "host2" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|
         vb.memory = "128"
         vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      end
      node.vm.hostname = "tenant1-host2"
      node.vm.network :private_network, virtualbox__intnet: "n9k2-eth12", mac: "0800F7760202", ip: "192.168.0.12", auto_config: false
      node.vm.provision "shell", inline: <<-SHELL
        ip addr add 192.168.0.12/24 dev eth1
      SHELL
  end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
